### ISSUE TITLE
B18 Noise map is 0 everywhere

### ISSUE THREAD

**Issue by low-sky** [jpinedaf/GAS#34] opened 2015-06-01 21:51 UTC
Something is wrong and this makes ammonia fitting barf.

**Comment by jpinedaf** [comment] 2015-06-12 15:31
I tested the code and it looks like it might be a problem with spectral cube. Below is a sample of the code that reproduces the issue:

```
import matplotlib.pyplot as plt
from spectral_cube import SpectralCube
from astropy import units as u
import numpy as np

file_in='B18_NH3_11_base1.fits'
cube = SpectralCube.read(file_in)

index_rms=np.arange(0,80)
mask_rms = np.zeros( cube.shape, dtype=bool)
mask_rms[index_rms] = True
#mask_rms = mask_rms & np.isfinite( (cube.unmasked_data[:,:,:]).value )
cube_rms = cube.with_mask(mask_rms)

rms1 = cube[0:80,:,:].std(axis=0)
rms2 = cube_rms.std(axis=0)

# plot map
plt.imshow( rms1.value,  origin='lower', vmin=0.01, vmax=0.4)
plt.show()

# plot map
plt.imshow( rms2.value, origin='lower', vmin=0.01, vmax=0.4)
plt.show()
```

The map rms1 produces the proper error map, 
![b18_rms1](https://cloud.githubusercontent.com/assets/6529114/8133456/b6b395f8-1128-11e5-92cd-3211e6858046.png)
but rms2 produces a flat map with zeros.
![b18_rms2](https://cloud.githubusercontent.com/assets/6529114/8133455/b6b330e0-1128-11e5-8867-53d79a90e080.png)

**Comment by jpinedaf** [comment] 2015-06-12 15:33
Taggin @keflavich... since he might have an idea of what is going on.

**Comment by keflavich** [comment] 2015-06-12 15:55
`mask_rms[index_rms] = True` doesn't look right to me; what is `mask_rms.sum()`?  I expect 80.

**Comment by keflavich** [comment] 2015-06-12 15:55
I think you want `mask_rms[index_rms,:,:] = True` ?  not sure if that works; if not, `mask_rms[:80,:,:]` ?

**Comment by jpinedaf** [comment] 2015-06-12 22:00
I tried your suggestions without success. In fact the original mask selection works just fine for the cube:
```
In [22]: mask_rms = np.zeros( cube.shape, dtype=bool)
In [23]: mask_rms[index_rms] = True
In [24]: mask_rms.sum()
Out[24]: 12135840
```

I also tried ``mask_rms[index_rms,:,:] = True`` and it gives the same rms image.

Notice that this code worked for all other regions imaged. Something is odd with the B18 data. BTW, the B18 data is available in the shared Google Drive Folder :)

**Comment by keflavich** [comment] 2015-06-13 12:54
OK, there is a bug here, and it appears to be something subtle:
```
In [58]: rms4 = cube_rms.std(axis=0, how='cube')

In [59]: np.nanmin(rms4), np.nanmax(rms4)
Out[59]: (<Projection 0.07533708327092394 K>, <Projection 787.0441990296787 K>)

In [60]: rms4 = cube_rms.std(axis=0, how='slice')
Cannot use how=slice. Using how=cube

In [61]: np.nanmin(rms4), np.nanmax(rms4)
Out[61]: (<Projection 0.0 K>, <Projection 0.0 K>)
```

**Comment by keflavich** [comment] 2015-06-14 19:15
I merged https://github.com/radio-astro-tools/spectral-cube/issues/211, which should fix this bug.

**Comment by jpinedaf** [comment] 2015-06-14 19:43
This indeed fixed the bug! Great.

**Closed by jpinedaf** 2015-06-14 19:43 UTC
Labels: bug, help wanted
